language: c
addons:
  apt:
    packages:
    - libncurses-dev
    - linux-headers-3.13.0-40-generic

cache:
  directories:
    - $HOME/dpdk

before_install:
  - cd $HOME/dpdk
  - wget http://fast.dpdk.org/rel/dpdk-16.11.1.tar.xz
  - tar --strip-components=1 -axvf dpdk-16.11.1.tar.xz
  - export RTE_KERNELDIR=/lib/modules/3.13.0-40-generic/build
  - make install T=x86_64-native-linuxapp-gcc
script:
  - export RTE_SDK=$HOME/dpdk
  - export RTE_TARGET=x86_64-native-linuxapp-gcc
  - make

